### ISSUE TITLE
Output MDC fields

### ISSUE THREAD

**Issue by haber-he** [Randgalt/maple#6]
Thank you so much opening source this great tools.

we have to output some generic fields such as requestId, userName. we put these generic fields in the MDC in the web filter. So should we add the mdc  annotation?  and we can use this annotation in the schema. such as:

```
@MDC("REQUEST_ID")
Schema requestId(String s);

@MDC("USER_NAME")
Schema userName(String s);
```
I known that we have the mdc method to control the mdc scope, it will be great if it can output the mdc fields that outside logger control.

please let me know your thoughts.

**Comment by Randgalt** [comment]
That's interesting but I don't understand how it would work? How do the values in those annotations translate into actual calls that set the MDC?

**Comment by haber-he** [comment]
I'm not familiar with this library, I just saw this great library today. 
draft thoughts probably not good or wrong, I will testing it later.

we can put values from MDC in the NamesValues in the StandardMapleSpi::consume method.

**Comment by Randgalt** [comment]
On my local machine I have a way of applying a Schema to MDC. I don't think the annotations would be necessary. I'll try to post something later

**Comment by Randgalt** [comment]
Doh - I forgot I already added it to the public project. Here's how it works:

```
@Path("whatever")
public class MyResource {
    private final MapleLogger<Schema> log = MapleFactory.getLogger(MyResource.class, Schema.class);

    @GET
    public void Thing getThing(CustomerId id, ThingId id) {
        try ( var mdc = log.mdc(s -> s.customerId(id).thingId(id)) ) {
            // process request
        }
    }
}
```

`log.mdc()` calls `MDC.put()` with the values and returns a Closeable that clears those values.

**Comment by haber-he** [comment]
Thank you @Randgalt, this is the nice solution for the method scope, but we can't use it for the global fields. such as USER_NAME and REQUEST_ID.
1. scenario is output the global fields to the log for the project scope, such as USER_NAME and REQUEST_ID.
2. I's suggest that add the prefix for the log.mdc, otherwise it will remove the other mdc field.

**Comment by Randgalt** [comment]
What you would do is define a separate Schema just for that. You can have multiple schema with Maple. So you'd make an MDC-only schema that has whatever naming you want. How about that? Otherwise, I think an `@MDC` annotation is too context specific. It seems to be renaming fields only when used with MDC. 

Another way to do it is with a custom `MapleFormatter` but I think the MDC-specific Schema would be easier.

**Comment by haber-he** [comment]
I'm trying to understand your saying.

Defining the MDC schema, and extends it.
```
public interface MDCSchema {
    @Required
    @Order(0)
    MDCSchema userName(String userName);
}

public interface Schema extends MDCSchema {
    Schema name(String name);
    Schema age(int age);
}

```

```
MDC.put("USER_NAME", "MDC-USER-NAME");
MapleLogger<Schema> logger = MapleFactory.getLogger(getClass(), Schema.class);
logger.info("test", s -> s.name("me").age(24).userName(MDC.get("USER_NAME")));
```

output 
```
age=24 name=me user_name=MDC-USER-NAME test
```


yes, it works, but all the logger have to setup the duplicated code.

```
.userName(MDC.get("USER_NAME")
```

**Comment by Randgalt** [comment]
Hmm - I may have a misunderstanding on how MDC works. Let me do some research and get back to you.

**Comment by Randgalt** [comment]
@HaberHe I've pushed an example of how to do MDC with Maple. Hopefully this is more clear. See #7

**Comment by haber-he** [comment]
@Randgalt, Thank you so much for your quickly example, this is what we're doing now in our product. this is simple and easy way to output generic fields for all the logs. I'm trying find the way to control these generic fields in the schema to make sure all the fields in one place.

**Comment by Randgalt** [comment]
I'm not sure what the benefit of putting them all in one place would be. You'd have to set them in every log statement which removes much of the benefit of MDC. Do I understand that you want some of the logging schema values to go to normal logging and others to go to MDC?

**Comment by Randgalt** [comment]
But, of course, you could always just add a few extra methods to your LoggingSchema and only ever use them for MDC:

```
...
log.mdc(s -> s.transactionId(id).transactionOwner(owner));

...

log.info(s -> s.name(name).code(code).etc(...));
```

**Comment by haber-he** [comment]
it will very useful in the multiple modules if defined the what we want output fields in the schema, each module have their different generic fields.
```
...
log.mdc(s -> s.transactionId(id).transactionOwner(owner));
...
log.info(s -> s.name(name).code(code).etc(...));
```
my concern is how to output what we defined generic MDC fields for all the logs that used schema, our current solutions are:

1. first, output the txId, txOwner in the logback.xml, this solution more focus on the project level generic fields.

2. second, output generic fields in each log.
```
log.info(s -> s.name("name1").code("code1").etc(...).transactionId(MDC.get("transactionId")).transactionOwner(MDC.get("transactionOwner")));

log.info(s -> s.name("name2").code("code2").etc(...).transactionId(MDC.get("transactionId")).transactionOwner(MDC.get("transactionOwner")));
```

i'm trying find the way, just defined the generic mdc fields in the schema. it can output these generic fields for all the logs that used this schema. it will very useful in the multiple modules, each module have their different generic fields.
```
log.info(s -> s.name("name1").code("code1").etc(...));
log.info(s -> s.name("name2").code("code2").etc(...));
```
output:
```
name=name1 code = code1 transactionId=transactionId transactionOwner=transactionOwner
name=name2 code = code2 transactionId=transactionId transactionOwner=transactionOwner
```

**Comment by haber-he** [comment]
i'm thinking the generic fields scope, probably can: 
- project level ->logback.xml such as, %X{transactionId}
- module level ->Schema?

**Comment by Randgalt** [comment]
If I understand, you'd use the MDC as a global logging value store so that you can extract values into each log statement? i.e. don't use logback.xml to have the MDC output, but have Maple insert the values?

**Comment by haber-he** [comment]
correct.

**Comment by Randgalt** [comment]
Interesting. Technically, we wouldn't have to use the MDC for it (it could be any ThreadLocal). Is there a benefit to using MDC?

**Comment by Randgalt** [comment]
OK - I added this. See #7

**Comment by haber-he** [comment]
Thank you so much for your patience and answer. it works for me.
